---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: app-team
  namespace: default
  description: The App Team group
spec:
  type: business-unit
  children: ["default/frontend-team", "backstage/maintainers"]
  members: ["default/akubicharm"]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  namespace: default
  description: The Backstage  Group
spec:
  children: ["maintainers"]
  type: team

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: maintainers
  namespace: default
  description: The Backstage maintainers Group
spec:
  parent: backstage
  type: team
