apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: myapp
  title: Example component for RHDH
  description: |
    This is the example component for RHDH
  links:
    - title: MyApp Website
      url: https://albumui-nodejs-sampleapp.apps.rosa.rosa-bb7nc.0no7.p3.openshiftapps.com/
    - title: MyApp Issues
      url: https://github.com/akubicharm/containerapps-albumui/issues
    - title: Wiki
      url: https://github.com/akubicharm/containerapps-albumui/wiki
    - title: OpenShift Console
      url: https://console-openshift-console.apps.rosa.rosa-bb7nc.0no7.p3.openshiftapps.com/k8s/cluster/projects/sampleapp
  annotations:
    backstage.io/kubernetes-namespace: sampleapp
    backstage.io/kubernetes-label-selector: 'app=albumui-nodejs'
spec:
  type: website
  system: myapp
  owner: myapp-dev-team
  lifecycle: production
  dependsOn:
    - resource:myappdb
