apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: myapp
  title: Example component for RHDH
  description: |
    This is the example component for RHDH
  links:
    - title: MyApp Website
      url: https://containerapps-albumui-sampleapp.apps.cluster-tlx6x.tlx6x.sandbox1448.opentlc.com/
    - title: MyApp Issues
      url: https://github.com/akubicharm/containerapps-albumui/issues
    - title: Wiki
      url: https://github.com/akubicharm/containerapps-albumui/wiki
    - title: Slack
      url: https://myapp.example.slack.com
  annotations:
    backstage.io/kubernetes-namespace: sampleapp
    backstage.io/kubernetes-label-selector: 'app=containerapps-albumui'
spec:
  type: website
  system: myapp
  owner: myapp-dev-team
  lifecycle: production
  dependsOn:
    - resource:myappdb
